
public class Drugi extends java.applet.Applet {

    /**
     * Initializes the applet Drugi
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        button1 = new java.awt.Button();
        label1 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        textField4 = new java.awt.TextField();
        textField6 = new java.awt.TextField();
        textField5 = new java.awt.TextField();
        textField7 = new java.awt.TextField();
        textField8 = new java.awt.TextField();
        textField9 = new java.awt.TextField();
        textField10 = new java.awt.TextField();
        textField11 = new java.awt.TextField();
        textField12 = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        label5 = new java.awt.Label();

        setLayout(null);
        add(textField1);
        textField1.setBounds(30, 30, 40, 40);

        button1.setBackground(new java.awt.Color(255, 102, 0));
        button1.setLabel("+");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(80, 30, 30, 40);

        label1.setText("=");
        add(label1);
        label1.setBounds(170, 220, 20, 40);
        add(textField2);
        textField2.setBounds(190, 30, 170, 40);
        add(textField3);
        textField3.setBounds(120, 30, 40, 40);
        add(textField4);
        textField4.setBounds(30, 90, 40, 40);
        add(textField6);
        textField6.setBounds(120, 90, 40, 40);
        add(textField5);
        textField5.setBounds(200, 90, 160, 40);
        add(textField7);
        textField7.setBounds(120, 220, 40, 50);
        add(textField8);
        textField8.setBounds(120, 150, 40, 50);
        add(textField9);
        textField9.setBounds(200, 220, 160, 50);
        add(textField10);
        textField10.setBounds(30, 140, 40, 50);
        add(textField11);
        textField11.setBounds(30, 220, 40, 50);
        add(textField12);
        textField12.setBounds(200, 150, 160, 50);

        label2.setText("=");
        add(label2);
        label2.setBounds(170, 30, 20, 40);

        label3.setText("=");
        add(label3);
        label3.setBounds(170, 90, 20, 40);

        label4.setText("=");
        add(label4);
        label4.setBounds(170, 160, 20, 40);

        button2.setBackground(new java.awt.Color(204, 0, 204));
        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button2.setLabel("-");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(80, 90, 30, 40);

        button3.setActionCommand("*");
        button3.setBackground(new java.awt.Color(0, 153, 51));
        button3.setLabel("*");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        add(button3);
        button3.setBounds(77, 150, 30, 40);

        button4.setBackground(new java.awt.Color(51, 51, 255));
        button4.setLabel("/");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        add(button4);
        button4.setBounds(80, 220, 30, 40);

        label5.setText("Kalkulator");
        add(label5);
        label5.setBounds(150, 0, 60, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        double x, y, z;
        String sx, sy, sz;

        sx = textField1.getText();
        sy = textField3.getText();

        // x = (int)z;
        try {

            x = Double.parseDouble(sx);
            y = Double.parseDouble(sy);
            z = x + y;
            sz = Double.toString(z);
        }
        catch (Exception e) {
            sz = "Przerwa";
            //e.printStackTrace();
        }

        textField2.setText(sz);
    
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        double x, y, z;
        String sx, sy, sz;

        sx = textField4.getText();
        sy = textField6.getText();

        // x = (int)z;
        try {

            x = Double.parseDouble(sx);
            y = Double.parseDouble(sy);
            z = x - y;
            sz = Double.toString(z);
        } catch (Exception e) {
            sz = "Przerwa";
            //e.printStackTrace();
        }

        textField5.setText(sz);
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        double x, y, z;
        String sx, sy, sz;

        sx = textField10.getText();
        sy = textField8.getText();

        // x = (int)z;
        try {

            x = Double.parseDouble(sx);
            y = Double.parseDouble(sy);
            z = x * y;
            sz = Double.toString(z);
        } catch (Exception e) {
            sz = "Przerwa";
            //e.printStackTrace();
        }

        textField12.setText(sz);
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        double x, y, z;
        String sx, sy, sz;

        sx = textField11.getText();
        sy = textField7.getText();

        // x = (int)z;
        try {

            x = Double.parseDouble(sx);
            y = Double.parseDouble(sy);
            z = x / y;
            sz = Double.toString(z);
        } catch (Exception e) {
            sz = "Przerwa";
            //e.printStackTrace();
        }

        textField9.setText(sz);
    }//GEN-LAST:event_button4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.TextField textField1;
    private java.awt.TextField textField10;
    private java.awt.TextField textField11;
    private java.awt.TextField textField12;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    private java.awt.TextField textField7;
    private java.awt.TextField textField8;
    private java.awt.TextField textField9;
    // End of variables declaration//GEN-END:variables
}
